UNWANTED_KEYWORDS = [
    "attach",
    "attachment",
    "list of attachments",
    "remove attachment",
    "submit",
    "check form",
    "modify",
    "sign",
    "digitally signed",
    "prescrutiny",
    "auto fill",
    "page",
    "button",
    "pre-fill",
    "click here",
    "download",
    "upload",
    "browse",
    "save",
    "print",
    "next",
    "previous",
    "continue",
    "cancel",
    "reset",
    "confirm",
    "agree",
    "decline",
    "accept",
    "reject",
    "approve",
    "deny",
    "refresh",
    "search",
    "filter",
    "sort",
    "expand",
    "collapse",
    "required field",
    "optional",
    "validation",
    "error",
    "warning",
    "success",
    "complete",
    "incomplete",
    "draft",
    "finalize",
    "lock",
    "unlock",
    "edit",
    "delete",
    "copy",
    "paste",
    "cut",
    "duplicate",
    "export",
    "import",
    "encrypt",
    "decrypt",
    "verify",
    "authentication",
    "authorization",
    "certificate",
    "timestamp",
    "watermark",
    "checksum",
    "hash",
    "biometric",
    "OTP",
    "2FA",
    "menu",
    "checkbox",
    "radio button",
    "toggle",
    "slider",
    "scroll",
    "zoom",
    "pan"
]